version: "3"
services:
  django_uwsgi:
    build:
      context: .
    container_name: cube_python_django_uwsgi_django
    environment:
      - CUBE_SAMPLE_MYSQL_HOST=mysql
      # New Relic agent will send data on https://<domain_of_cubeapm_server>:443
      - NEW_RELIC_HOST=<domain_of_cubeapm_server>
      - NEW_RELIC_APP_NAME=cube_sample_python_django_uwsgi_newrelic
      - NEW_RELIC_LICENSE_KEY=ABC4567890ABC4567890ABC4567890ABC4567890
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis
    restart: always

  mysql:
    image: mysql:8.0
    container_name: cube_python_django_uwsgi_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    volumes:
      - cube_python_django_uwsgi_mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine3.18
    container_name: cube_python_django_uwsgi_redis

volumes:
  cube_python_django_uwsgi_mysql:
