version: "3"
services:
  django_uwsgi:
    build:
      context: .
    container_name: cube_python_django_uwsgi_django
    environment:
      - CUBE_SAMPLE_MYSQL_HOST=mysql

      - DD_SERVICE=cube_sample_python_django_uwsgi_datadog
      # send traces to CubeAPM
      - DD_TRACE_AGENT_URL=http://host.docker.internal:3130

      # optional settings
      # - DD_ENV=myenv
      # - DD_VERSION=1.2.3
      # - DD_TAGS=mykey1:myvalue1,mykey2:myvalue2

      # Print Datadog tracer startup logs on screen
      # - DD_TRACE_STARTUP_LOGS=true
      # Enable Datadog tracer debug logging if needed to see detailed logs
      # - DD_TRACE_DEBUG=true
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis
    restart: always

  mysql:
    image: mysql:8.0
    container_name: cube_python_django_uwsgi_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    volumes:
      - cube_python_django_uwsgi_mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine3.18
    container_name: cube_python_django_uwsgi_redis

volumes:
  cube_python_django_uwsgi_mysql:
