version: "3"
services:
  django_uwsgi:
    build:
      context: .
    container_name: cube_python_django_uwsgi_django
    environment:
      - CUBE_SAMPLE_MYSQL_HOST=mysql

      - ELASTIC_APM_SERVICE_NAME=cube_sample_python_django_uwsgi_elastic
      - ELASTIC_APM_SERVER_URL=http://host.docker.internal:3130

      # optional settings
      # - ELASTIC_APM_ENVIRONMENT=myenv
      # - ELASTIC_APM_SERVICE_VERSION=1.2.3
      # - ELASTIC_APM_GLOBAL_LABELS=mykey1=myvalue1,mykey2=myvalue2

      # Not needed for production - https://www.elastic.co/guide/en/apm/agent/python/current/configuration.html#config-debug
      - ELASTIC_APM_DEBUG=True

      # Print Elastic agent logs on screen (also see wsgi.py for additional requirements)
      # - ELASTIC_APM_LOG_FILE=stdout
      # Set Elastic agent log level to debug if needed to see detailed logs
      # - ELASTIC_APM_LOG_LEVEL=debug
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis
    restart: always

  mysql:
    image: mysql:8.0
    container_name: cube_python_django_uwsgi_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    volumes:
      - cube_python_django_uwsgi_mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine3.18
    container_name: cube_python_django_uwsgi_redis

volumes:
  cube_python_django_uwsgi_mysql:
